runtime: python38
entrypoint: gunicorn -b :$PORT lmnop_project.wsgi

handlers:
- url: /static
  static_dir: www/static

- url: /.*
  script: auto

env_variables:
  LMNOP_DB_PW: XaWG9yyj2QyecGCD

beta_settings:
  cloud_sql_instances: lmnop-275222:us-central1:lmnop-db