# Generated by Django 2.1.11 on 2020-05-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0004_profile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fav_band',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='insta_username',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='snap_username',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitch_username',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_username',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
