# Generated by Django 2.1.11 on 2020-05-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0005_auto_20200505_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fav_band',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='insta_username',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='snap_username',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitch_username',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='youtube_username',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
