# Generated by Django 2.1.11 on 2020-05-10 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0007_auto_20200429_1229'),
        ('lmn', '0006_auto_20200505_2339'),
    ]

    operations = [
    ]
