# Generated by Django 3.0.4 on 2020-05-11 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0007_auto_20200429_1229'),
        ('lmn', '0006_auto_20200505_2339'),
    ]

    operations = [
    ]
